version: '3.8'
services:

  mysql:
    image: mysql:8.0
    container_name: projectionsql
    restart: always
    environment:
      - MYSQL_DATABASE=projectiondb
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    networks:
      - my-projections

networks:
  my-projections:
    driver: bridge